version: '3'

services:
  redis:
    image: "redis:latest"
    command: redis-server
  db:
    image: postgres:10.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  api:
    build:
      context: .
      dockerfile: Dockerfile.dev
    command: bash -c "python manage.py migrate  && python manage.py initadmin && python manage.py runserver 0.0.0.0:8000"
    container_name: stockman_api

    ports:
      - "8000:8000"
    environment:
      - USE_S3=${USE_S3}
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_STORAGE_BUCKET_NAME=${AWS_STORAGE_BUCKET_NAME}
    depends_on:
      - db
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.dev
    restart: always
    ports:
      - '3050:80'
    depends_on:
      - api


volumes:
  postgres_data: