version: '3'

services:
  redis:
    image: "redis:latest"
    command: redis-server
  db:
    image: postgres:10.1-alpine
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=${DATABASE_USER}
      - POSTGRES_PASSWORD=${DATABASE_PASSWORD}
      - POSTGRES_DB=${DATABASE_NAME}
    restart: always
    volumes:
      - postgres_data:/var/lib/postgresql/data/
  server:
    build:
      context: .
      dockerfile: .docker/server/Dockerfile
    command: bash -c "python manage.py migrate && python manage.py runserver 127.0.0.1:8000"
    container_name: stockman_api
    volumes:
      - .:/usr/src/app/
    ports:
      - "8080:8000"
    depends_on:
      - db


volumes:
  postgres_data: