# Generated by Django 2.1.4 on 2018-12-23 17:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Industry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('exchange_code', models.CharField(max_length=50)),
                ('sync_flag', models.CharField(max_length=30)),
                ('logo', models.CharField(max_length=10)),
            ],
        ),
    ]
