# Generated by Django 2.1.4 on 2018-12-24 12:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stock_setup_info', '0003_auto_20181223_2151'),
    ]

    operations = [
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stock_code', models.CharField(max_length=50)),
                ('name', models.CharField(max_length=50)),
                ('exchange_code', models.CharField(max_length=50)),
                ('asset_class_code', models.CharField(max_length=50)),
                ('contact', models.CharField(max_length=50)),
                ('description', models.CharField(max_length=50)),
                ('tier_code', models.CharField(max_length=50)),
                ('par_value', models.CharField(max_length=50)),
                ('list_date', models.DateField(max_length=50)),
                ('outstanding_shares', models.CharField(max_length=50)),
                ('grp_code', models.CharField(max_length=50)),
                ('registrar', models.CharField(max_length=50)),
                ('address_1', models.CharField(max_length=50)),
                ('address_2', models.CharField(max_length=50)),
                ('address_3', models.CharField(max_length=50)),
                ('state_code', models.CharField(max_length=50)),
                ('website', models.CharField(max_length=250)),
                ('email', models.CharField(max_length=250)),
                ('gsm', models.CharField(max_length=150)),
                ('land_tel', models.CharField(max_length=50)),
                ('fax_no', models.CharField(max_length=50)),
                ('regis_close', models.DateField(max_length=50)),
                ('year_end', models.CharField(max_length=50)),
                ('logo', models.CharField(max_length=50)),
                ('shares_in_issue', models.BigIntegerField()),
                ('capitalization', models.BigIntegerField()),
                ('view_count', models.BigIntegerField()),
                ('is_active', models.BooleanField()),
                ('industry', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stocks', to='stock_setup_info.Industry')),
            ],
        ),
        migrations.AlterField(
            model_name='structure',
            name='is_active',
            field=models.BooleanField(),
        ),
        migrations.AddField(
            model_name='stock',
            name='structure_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stock_structure', to='stock_setup_info.Structure'),
        ),
    ]
