# Generated by Django 2.1.4 on 2018-12-24 12:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_setup_info', '0004_auto_20181224_1215'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='structure_type',
            new_name='structure',
        ),
    ]
