# Generated by Django 2.1.4 on 2018-12-24 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_setup_info", "0005_auto_20181224_1217"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="structure",
            name="parent_id",
        ),
        migrations.AlterField(
            model_name="structure",
            name="structure_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="structuretype",
            name="description",
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
