# Generated by Django 2.1.4 on 2018-12-27 09:31

from django.db import migrations, models
import enumchoicefield.fields
import stock_setup_info.models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_setup_info", "0008_auto_20181226_1712"),
    ]

    operations = [
        migrations.CreateModel(
            name="StockManagement",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=250)),
                ("position", models.CharField(max_length=250)),
                (
                    "management_type",
                    enumchoicefield.fields.EnumChoiceField(
                        default=stock_setup_info.models.ManagementType(1),
                        enum_class=stock_setup_info.models.ManagementType,
                        max_length=10,
                    ),
                ),
                ("is_active", models.BooleanField()),
            ],
        ),
    ]
