# Generated by Django 2.1.4 on 2019-01-15 16:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_setup_info', '0013_auto_20190102_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='structuretype',
            name='description',
            field=models.CharField(blank=True, max_length=2000, null=True),
        ),
    ]
