# Generated by Django 2.1.4 on 2019-01-24 10:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_setup_info", "0017_auto_20190124_1033"),
    ]

    operations = [
        migrations.RenameField(
            model_name="structure",
            old_name="parent_id",
            new_name="parent",
        ),
        migrations.RenameField(
            model_name="structuretype",
            old_name="parent_id",
            new_name="parent",
        ),
    ]
