# Generated by Django 2.1.4 on 2019-01-25 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_setup_info", "0019_auto_20190124_2315"),
    ]

    operations = [
        migrations.AlterField(
            model_name="stock",
            name="address_1",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="address_2",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="address_3",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="asset_class_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="capitalization",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="contact",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="description",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="email",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="exchange_code",
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="fax_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="grp_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="gsm",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="land_tel",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="logo",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="par_value",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="registrar",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="shares_in_issue",
            field=models.BigIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="stock",
            name="state_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="tier_code",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="website",
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name="stock",
            name="year_end",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
