# Generated by Django 2.1.4 on 2019-01-25 12:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_setup_info', '0021_auto_20190125_1157'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='outstanding_shares',
            field=models.DecimalField(decimal_places=2, max_digits=19, null=True),
        ),
    ]
