# Generated by Django 2.1.4 on 2019-01-25 12:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_setup_info', '0023_auto_20190125_1201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stock',
            name='capitalization',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='shares_in_issue',
            field=models.BigIntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='stock',
            name='view_count',
            field=models.BigIntegerField(default=0, null=True),
        ),
    ]
