# Generated by Django 2.1.4 on 2020-12-14 14:23

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stock_setup_info", "0031_auto_20200706_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="stockmanagement",
            name="stock_code",
            field=models.CharField(default=django.utils.timezone.now, max_length=150),
            preserve_default=False,
        ),
    ]
