# Generated by Django 2.1.4 on 2018-12-27 09:31

from django.db import migrations, models
import django.db.models.deletion
import enumchoicefield.fields
import stock_maintain.models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_setup_info', '0009_stockmanagement'),
        ('stock_maintain', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AsiIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('price_open', models.FloatField()),
                ('price_high', models.FloatField()),
                ('price_low', models.FloatField()),
                ('price_close', models.FloatField()),
                ('price_current', models.FloatField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='BonusTracker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_code', models.CharField(max_length=10)),
                ('bonus_val', models.SmallIntegerField()),
                ('bonus_aggregate', models.SmallIntegerField()),
                ('date_declared', models.DateField()),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='bonus_stock', to='stock_setup_info.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='DailyMarketIndex',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('index', models.FloatField()),
                ('deals', models.FloatField()),
                ('volume', models.FloatField()),
                ('value', models.FloatField()),
                ('capital', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Dividend',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_code', models.CharField(max_length=10)),
                ('quarter_type', enumchoicefield.fields.EnumChoiceField(default=stock_maintain.models.QuarterType(1), enum_class=stock_maintain.models.QuarterType, max_length=14)),
                ('interim', models.FloatField()),
                ('bonus', models.FloatField()),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='dividend_stock', to='stock_setup_info.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('content', models.CharField(max_length=10)),
                ('date', models.DateField()),
                ('entry_date', models.DateField()),
                ('sec_code', models.CharField(max_length=10)),
                ('is_featured', models.BooleanField()),
                ('author', models.CharField(max_length=100, null=True)),
                ('news_section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_structure', to='stock_setup_info.Structure')),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='news_stock', to='stock_setup_info.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='NewsImages',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField()),
                ('image_file', models.FileField(blank=True, upload_to='images/news_image')),
                ('name', models.CharField(max_length=100)),
                ('news_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='visual_news', to='stock_setup_info.Stock')),
            ],
        ),
        migrations.CreateModel(
            name='OfferIpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company_name', models.CharField(max_length=150)),
                ('exchange_code', models.CharField(max_length=10)),
                ('offer_type', enumchoicefield.fields.EnumChoiceField(default=stock_maintain.models.OfferType(3), enum_class=stock_maintain.models.OfferType, max_length=4)),
                ('quarter_type', enumchoicefield.fields.EnumChoiceField(default=stock_maintain.models.OfferMethod(1), enum_class=stock_maintain.models.OfferMethod, max_length=3)),
                ('open_date', models.DateField(null=True)),
                ('close_date', models.DateField(null=True)),
                ('extended_date', models.DateField(null=True)),
                ('proposed_listing_date', models.DateField(null=True)),
                ('actual_listing_date', models.DateField(null=True)),
                ('country_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='country', to='stock_setup_info.Structure')),
            ],
        ),
        migrations.CreateModel(
            name='Quotes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sec_code', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('contact', models.CharField(max_length=100)),
                ('fax', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=100)),
                ('stock_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='quotes_stock', to='stock_setup_info.Stock')),
            ],
        ),
        migrations.AddField(
            model_name='pricelist',
            name='stock_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='price_stock', to='stock_setup_info.Stock'),
        ),
        migrations.AlterField(
            model_name='pricelist',
            name='price_date',
            field=models.DateField(),
        ),
    ]
