# Generated by Django 2.1.4 on 2019-01-01 17:23

from django.db import migrations
import enumchoicefield.fields
import stock_maintain.models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0004_auto_20181231_0941"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsimage",
            name="image_type",
            field=enumchoicefield.fields.EnumChoiceField(
                default=stock_maintain.models.ImageSizeType(1),
                enum_class=stock_maintain.models.ImageSizeType,
                max_length=11,
            ),
        ),
    ]
