# Generated by Django 2.1.4 on 2019-01-02 09:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0005_newsimage_image_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='is_main',
            field=models.BooleanField(default=False),
        ),
    ]
