# Generated by Django 2.1.4 on 2019-01-25 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0011_pricelist_x_change"),
    ]

    operations = [
        migrations.RenameField(
            model_name="pricelist",
            old_name="stock_id",
            new_name="stock",
        ),
    ]
