# Generated by Django 2.1.4 on 2019-01-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0012_auto_20190125_1330"),
    ]

    operations = [
        migrations.AlterField(
            model_name="pricelist",
            name="num_of_deals",
            field=models.FloatField(),
        ),
    ]
