# Generated by Django 2.1.4 on 2019-02-24 18:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0019_auto_20190130_1520"),
    ]

    operations = [
        migrations.AlterField(
            model_name="author",
            name="description",
            field=models.CharField(max_length=450),
        ),
    ]
