# Generated by Django 2.1.4 on 2019-12-28 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0028_auto_20191228_1833'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='pricelist',
            name='e_date',
        ),
        migrations.RemoveField(
            model_name='pricelist',
            name='e_time',
        ),
    ]
