# Generated by Django 2.1.4 on 2020-02-18 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0031_auto_20200130_0645'),
    ]

    operations = [
        migrations.AlterField(
            model_name='analysisimage',
            name='image_type',
            field=models.CharField(choices=[('size930x620', 'size930x620'), ('size450x330', 'size450x330'), ('size300x200', 'size300x200'), ('size158x158', 'size158x158')], default='size930x620', max_length=30),
        ),
        migrations.AlterField(
            model_name='insidebusinessimage',
            name='image_type',
            field=models.CharField(choices=[('size930x620', 'size930x620'), ('size450x330', 'size450x330'), ('size300x200', 'size300x200'), ('size158x158', 'size158x158')], default='size930x620', max_length=30),
        ),
    ]
