# Generated by Django 2.1.4 on 2020-03-26 11:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stock_maintain', '0033_newslettermailing'),
    ]

    operations = [
        migrations.AlterField(
            model_name='newslettermailing',
            name='email',
            field=models.TextField(unique=True),
        ),
    ]
