# Generated by Django 2.1.4 on 2020-10-03 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0038_auto_20200706_2028"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceanalysistemp",
            name="price_year_to_date_cent",
            field=models.FloatField(null=True),
        ),
    ]
