# Generated by Django 2.1.4 on 2020-10-08 23:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0039_priceanalysistemp_price_year_to_date_cent"),
    ]

    operations = [
        migrations.AddField(
            model_name="priceanalysistemp",
            name="price_52_week_high",
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name="priceanalysistemp",
            name="price_52_week_low",
            field=models.FloatField(null=True),
        ),
    ]
