# Generated by Django 2.1.4 on 2020-10-28 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0041_dividendinformation_quarterlyfinancial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quarterlyfinancial",
            name="previous_net_assets",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quarterlyfinancial",
            name="previous_profit_after_tax",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quarterlyfinancial",
            name="previous_total_assets",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="quarterlyfinancial",
            name="previous_turnover",
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
