# Generated by Django 2.1.4 on 2020-10-29 14:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0042_auto_20201028_1844"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividendinformation",
            name="year",
            field=models.IntegerField(default=2020),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="dividendinformation",
            name="dividend_type",
            field=models.CharField(
                choices=[("Interim", "Interim"), ("Final", "Final")],
                default="Final",
                max_length=50,
            ),
        ),
    ]
