# Generated by Django 2.1.4 on 2020-10-29 14:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0043_auto_20201029_1521"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividendinformation",
            name="dividend_value",
            field=models.FloatField(default=0.01),
            preserve_default=False,
        ),
    ]
