# Generated by Django 2.1.4 on 2020-10-29 19:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("stock_maintain", "0044_dividendinformation_dividend_value"),
    ]

    operations = [
        migrations.AddField(
            model_name="dividendinformation",
            name="payment_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="dividendinformation",
            name="qualification_date",
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
